apiVersion: v1
kind: Pod
metadata:
  name: deliveryservice
  labels:
    app.kubernetes.io/name: deliveryservice
spec:
  containers:
    - name: test-end
      image: f2js/deliveryservice:latest
      ports:
        - containerPort: 8080
