apiVersion: v1
kind: Pod
metadata:
  name: cour-delivery-temp
  labels:
    app.kubernetes.io/name: cour-delivery-temp
spec:
  containers:
    - name: cour-delivery-temp
      image: f2js/cour-delivery:latest
      env:
        - name: "TOKEN_SECRET"
          value: ${TOKEN_SECRET}
        - name: "DB_URI"
          value: ${DB_URI}
        - name: "DB_NAME"
          value: ${DB_NAME}
        - name: "NODE_ENV"
          value: production
        - name: "KAFKA_BROKER"
          value: ${KAFKA_BROKER}
      ports:
        - containerPort: 3000
