apiVersion: v1
kind: Service
metadata:
  name: cour-delivery-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "${CERT}"
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
    - nodePort: 0 # - a static port assigned on each the node
    - name: graphql
      port: 4000
      targetPort: 4000
    - name: rest
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: cour-delivery
