apiVersion: v1
kind: Service
metadata:
  name: cour-delivery-service
  namespace: default
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
    - nodePort: 0 # - a static port assigned on each the node
      port: 4000 # - port exposed internally in the cluster
      targetPort: 4000 # - the container port to send requests to
  selector:
    app.kubernetes.io/name: cour-delivery
