apiVersion: v1
kind: Service
metadata:
  name: cour-delivery-service
  namespace: default
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
    - name: "graphql"
      port: 4001
      targetPort: 4001
    - name: "rest"
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: cour-delivery